name: OCI DSPSR builder image build

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - ".github/workflows/dspsr-builder-oci-build.yml"
      - "images/dspsr-builder/**"
      - "resources/dspsr"
  workflow_dispatch: {}

env:
  OCI_REGISTRY: ocr.jcan.dev/library
  OCI_IMAGE_NAME: dspsr-builder
  SUBMODULE_NAME: dspsr

jobs:
  dspsr-builder-oci-build-and-publish:
    runs-on:
      group: homelab
      labels: ghar-scale-set
    container:
      image: ghcr.io/actions/actions-runner:2.328.0
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Delegate build process to Argo Workflow
        run: |
          # Extract OCI image tag from submodules.json
          OCI_IMAGE_TAG=$(jq -r ".${SUBMODULE_NAME}.tag" submodules.json)

          echo "Using tag: $OCI_IMAGE_TAG"

          # Trigger Argo Workflow build
          curl 'https://wf.jcan.dev/wf/webhooks/buildkit' \
            -H 'Content-Type: application/json' \
            -H "Authorization: ${{ secrets.ARGOWF_BEARER_TOKEN }}" \
            -d "{
                \"repo\": \"${{ github.server_url }}/${{ github.repository }}.git\",
                \"branch\": \"main\",
                \"dockerfile\": \"images/${{ env.OCI_IMAGE_NAME }}\",
                \"image\": \"${{ env.OCI_REGISTRY }}/${{ env.OCI_IMAGE_NAME }}:${OCI_IMAGE_TAG}\",
                \"context\": \"./\"
              }"
