name: Update Submodules

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - "submodules.json"

jobs:
  update-submodules:
    runs-on:
      group: homelab
      labels: ghar-scale-set
    container:
      image: ghcr.io/actions/actions-runner:2.328.0
 
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0            # get full history of parent repo
          submodules: recursive     # also fetch submodules
          set-safe-directory: true

      - name: Configure Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Run update-submodule.sh
        run: |
          chmod +x ./tools/scripts/update-submodule.sh
          ./tools/scripts/update-submodule.sh

      - name: Commit and push changes
        run: |
          if [[ -n "$(git status --porcelain resources)" ]]; then
            git add resources/*
            git commit -m "ci: update submodules"
            git push origin HEAD:${{ github.head_ref }}
          else
            echo "No submodule updates detected."
          fi